### ISSUE TITLE
How can generate and install a selfsigned certificate?

### ISSUE THREAD

**Issue by etcware** [uthsc/UTHSC-WPCAS#5]
thanks
Alessandra

**Comment by gpspake** [comment]
Hi @etcware, I'm so sorry I missed this.
I think that question might be outside the scope of this project and, admittedly, I don't usually deal with setting our certs up so I might not be the best person to ask.
I'm going to close this issue because it's been a while and I don't think I can help much but feel free to submit a new one if you need any additional help with the plugin. Thx
